/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.spring.cloud.circuitbreaker;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        CircuitBreakerApplication classUnderTest = new CircuitBreakerApplication();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
