/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.spring.cloud.web1;

import org.junit.jupiter.api.Test;

public class Web1ApplicationTest {
    @Test
    public void testAppHasAGreeting() {
    }
}
